# author = "Moses Narrow"
baseURL = "http://127.0.0.1:8041/"
languageCode = "en-us"
title = "skycoin"
#theme = "sky"

[menu]
[[menu.header]]
 identifier = "time"
 name = "{{fdateMDY}}"
 url = "" # The path can lead to a content folder too.
 weight = 0

[params]
 CryptoName = "{{.CryptoName}}"
 Ticker = "{{.Ticker}}"
 #siteHeading = "skycoin payment"
 #mainpagetitle = "Pay with Skycoin"
 QRCode = "{{.QRCode}}"
 QRImage = "<img class=\"media-object dp\" src=\"data:image/png;base64,{{ .QRCode }}\" style=\"width: 256px;height:256px;\">"
 Address = "{{.Address}}"
 Amount = "{{.Amount}}"
 UsdAmount = "{{.UsdAmount}}"
 UsdAmount1 = "<input type=\"hidden\" name=\"price\" value=\"{{.UsdAmount}}\" />"
 IfNotBTC = "{{ if ne .CryptoName \"Bitcoin\"}}"
 BTCPay = "<form method=\"POST\" onsubmit=\"onBTCPayFormSubmit(event);return false\" action=\"https://btc.magnetosphere.net/api/v1/invoices\" class=\"btcpay-form btcpay-form--block\">	<input type=\"hidden\" name=\"storeId\" value=\"5VrWYtRDGfraCA9A9xfsNizEt6moU5hZyG1pShrJS3Cv\" />	<input type=\"hidden\" name=\"jsonResponse\" value=\"true\" />{{ .UsdAmount }}<input type=\"hidden\" name=\"currency\" value=\"USD\" /> <input type=\"image\" class=\"submit\" name=\"submit\" src=\"http://magnetosphere.net/img/pay.png\" style=\"width:209px\" alt=\"Pay with Bitcoin\"></form>"
 IfInvoice = "{{ if ne .Invoice \"\"}}"
 Invoice = "{{.Invoice}}"
 end = "{{end}}"
 else = "{{else}}"
